### Carregando Dados

In [1]:
import pandas as pd
import ast

In [2]:
features = pd.read_csv('../Results/feature_selection.csv').drop(columns=['Unnamed: 0'])
features.head()

,method,n_features,selected_features,rmse_mean,rmse_std,r2_mean,r2_std,alpha
0,RFS_forward,15,"['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MA...",0.337976,0.008069,0.104115,0.045558,NaN
1,RFS_forward,13,"['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MA...",0.338072,0.008906,0.103565,0.048478,NaN
2,RFS_forward,12,"['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MA...",0.338166,0.008892,0.102998,0.049818,NaN
3,RFS_forward,14,"['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MA...",0.338331,0.008414,0.102233,0.046463,NaN
4,RFE,11,"['PROP_ESC_URBANA', 'PROP_MAT_PRETA', 'PROP_MA...",0.338482,0.009082,0.101184,0.052727,NaN

In [3]:
df = pd.read_csv('../Datasets/Dados/VIF - Final até agora/dataset_modelo_2022.csv', sep=';')

In [4]:
df = df[ast.literal_eval(features.iloc[0]['selected_features']) + ['TAXA_CRE_INT', 'NO_MUNICIPIO', 'SG_UF']]

### One Hot Encoding

In [5]:
df = pd.get_dummies(
    df,
    columns=['SG_UF'],
    drop_first=False,
    dtype=int
)

### Train, Val, Test Split

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X = df.drop(columns=['TAXA_CRE_INT'])
y = df['TAXA_CRE_INT']

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

val_relative_size = 0.2 / (1 - 0.2)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val,
    y_train_val,
    test_size=val_relative_size,
    random_state=42
)

### Normalização

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
def scale_cols(X_train, X_val, X_test, columns):
    X_train_scaled = X_train.copy()
    X_val_scaled = X_val.copy()
    X_test_scaled = X_test.copy()

    scaler = StandardScaler()

    X_train_scaled[columns] = scaler.fit_transform(X_train_scaled[columns])
    X_val_scaled[columns] = scaler.transform(X_val_scaled[columns])
    X_test_scaled[columns] = scaler.transform(X_test_scaled[columns])

    return X_train_scaled, X_val_scaled, X_test_scaled, scaler

In [10]:
X_train_scaled, X_val_scaled, X_test_scaled, scaler = scale_cols(
    X_train=X_train,
    X_val=X_val,
    X_test=X_test,
    columns=ast.literal_eval(features.iloc[0]['selected_features'])
    )

### AutoML com AutoGluon

In [16]:
from autogluon.tabular import TabularPredictor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from tqdm import tqdm
import os
import shutil

In [13]:
def prepare_autogluon_data(X, y, target_column):
    data = X.copy()
    data[target_column] = y.values
    return data

In [18]:
def run_automl(
    X_train,
    y_train,
    X_val,
    y_val,
    X_test,
    y_test,
    target_column,
    id_column=None,
    output_path="autogluon_regression",
    time_limit=600,
    overwrite=True
):
    if overwrite and os.path.exists(output_path):
        shutil.rmtree(output_path)

    if id_column is not None:
        X_train = X_train.drop(columns=[id_column], errors="ignore")
        X_val = X_val.drop(columns=[id_column], errors="ignore")
        X_test = X_test.drop(columns=[id_column], errors="ignore")

    train_data = prepare_autogluon_data(X_train, y_train, target_column)
    val_data = prepare_autogluon_data(X_val, y_val, target_column)

    train_full = pd.concat(
        [train_data, val_data],
        ignore_index=True
    )

    test_data = prepare_autogluon_data(X_test, y_test, target_column)

    predictor = TabularPredictor(
        label=target_column,
        problem_type="regression",
        eval_metric="root_mean_squared_error",
        path=output_path
    )

    predictor.fit(
        train_data=train_full,
        time_limit=time_limit,
        presets="best_quality"
    )

    X_test_final = test_data.drop(columns=[target_column])

    predictions = predictor.predict(X_test_final)

    rmse = np.sqrt(mean_squared_error(y_test, predictions))
    mae = mean_absolute_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)

    metrics = {
        "rmse": rmse,
        "mae": mae,
        "r2": r2
    }

    leaderboard = predictor.leaderboard(
        test_data,
        silent=True
    )

    return predictor, metrics, leaderboard, predictions

In [19]:
predictor, metrics, leaderboard, predictions = run_automl(
    X_train=X_train_scaled,
    y_train=y_train,
    X_val=X_val_scaled,
    y_val=y_val,
    X_test=X_test_scaled,
    y_test=y_test,
    target_column="TAXA_CRE_INT",
    id_column="NO_MUNICIPIO",
    output_path="autogluon_regression",
    time_limit=3600
)

Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.11.15
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Wed May 27 14:05:53 UTC 2026
CPU Count:          16
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       7.15 GB / 15.23 GB (46.9%)
Disk Space Avail:   59.58 GB / 182.28 GB (32.7%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 900s of the 3600s of remaining time (25%).
		Context path: "/home/guilherme_fernandes/Aprendizagem_Autom-tica_UFC_2026.1/criancas_creche/Notebooks/autogluon_regression/ds_sub_fit/sub_fit_ho"
Leaderboard on holdout data (DyStack):
                           model  score_holdout  score_val              eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0    NeuralNetFastAI_r100_BAG_L1      -0.312673  -0.312996  root_mean_squared_error        0.148708       0.172386  17.965816                 0.148708                0.172386          17.965816            1       True         97
1            LightGBM_r42_BAG_L1      -0.315617  -0.311503  root_mean_squared_error        0.012950       0.009192   1.171242                 0.012950                0.009192           1.171242            1       True        104
2           LightGBM_r188_BAG_L1      -0.315919  -0.310252  root_mean_squared_error        0.018889       0.011994   2.013766                 0.018889                0.011994           2.013766            1       True         23
3            LightGBM_r94_BAG_L1      -0.316880  -0.309771  root_mean_squared_error        0.015919       0.015538   0.999031                 0.015919                0.015538           0.999031            1       True         57
4           LightGBM_r196_BAG_L1      -0.317021  -0.309014  root_mean_squared_error        0.123178       0.073913   5.227637                 0.123178                0.073913           5.227637            1       True         40
5            CatBoost_r13_BAG_L2      -0.317330  -0.304428  root_mean_squared_error        1.145877       0.717202  60.318701                 0.012641                0.051708          20.977296            2       True        128
6    NeuralNetFastAI_r172_BAG_L1      -0.317417  -0.309573  root_mean_squared_error        0.068229       0.059284   3.710758                 0.068229                0.059284           3.710758            1       True         84
7     NeuralNetFastAI_r69_BAG_L1      -0.317495  -0.307672  root_mean_squared_error        0.094180       0.081130   4.207442                 0.094180                0.081130           4.207442            1       True         80
8    NeuralNetFastAI_r191_BAG_L1      -0.317627  -0.316893  root_mean_squared_error        0.082291       0.165484   6.504111                 0.082291                0.165484           6.504111            1       True         13
9    NeuralNetFastAI_r138_BAG_L1      -0.317763  -0.311897  root_mean_squared_error        0.093299       0.155979   7.734386                 0.093299                0.155979           7.734386            1       True         82
10           LightGBM_r30_BAG_L1      -0.317893  -0.308591  root_mean_squared_error        0.033889       0.026206   1.709360                 0.033889                0.026206           1.709360            1       True         65
11           LightGBM_r96_BAG_L1      -0.318120  -0.308864  root_mean_squared_error        0.029340       0.035609   1.713913                 0.029340                0.035609           1.713913            1       True         15
12             LightGBMXT_BAG_L1      -0.318165  -0.308669  root_mean_squared_error        0.199550       0.009095   1.240285                 0.199550                0.009095           1.240285            1       True          1
13           CatBoost_r86_BAG_L1      -0.318207  -0.312459  root_mean_squared_error        0.021685       0.012360   8.415759                 0.021685                0.012360           8.415759            1       True         48
14          CatBoost_r167_BAG_L2      -0.318293  -0.304443  root_mean_squared_error        1.143081       0.710511  44.362110                 0.009845                0.045017           5.020706            2       True        149
15        ExtraTrees_r178_BAG_L1      -0.318366  -0.309820  root_mean_squared_error        0.045969       0.054065   0.926791                 0.045969                0.054065           0.926791            1       True         71
16   NeuralNetFastAI_r103_BAG_L1      -0.318464  -0.313201  root_mean_squared_error        0.073976       0.064647   4.319628                 0.073976                0.064647           4.319628            1       True         34
17               CatBoost_BAG_L2      -0.318717  -0.304258  root_mean_squared_error        1.145922       0.703353  42.841770                 0.012687                0.037859           3.500366            2       True        111
18         ExtraTrees_r42_BAG_L2      -0.318774  -0.305740  root_mean_squared_error        1.192109       0.725278  39.907546                 0.058874                0.059783           0.566142            2       True        125
19     NeuralNetFastAI_r4_BAG_L1      -0.318827  -0.308516  root_mean_squared_error        0.068199       0.053524   3.969176                 0.068199                0.053524           3.969176            1       True         94
20    NeuralNetFastAI_r37_BAG_L1      -0.318850  -0.308827  root_mean_squared_error        0.074058       0.066608   5.104085                 0.074058                0.066608           5.104085            1       True         49
21    NeuralNetFastAI_r11_BAG_L1      -0.318875  -0.309276  root_mean_squared_error        0.094840       0.093335   7.864901                 0.094840                0.093335           7.864901            1       True         30
22           CatBoost_r13_BAG_L1      -0.318982  -0.313487  root_mean_squared_error        0.028472       0.011319  11.975194                 0.028472                0.011319          11.975194            1       True         21
23           CatBoost_r69_BAG_L2      -0.318992  -0.303819  root_mean_squared_error        1.143886       0.696126  41.602553                 0.010651                0.030632           2.261148            2       True        140
24         ExtraTrees_r42_BAG_L1      -0.319018  -0.312608  root_mean_squared_error        0.087615       0.057845   0.559323                 0.087615                0.057845           0.559323            1       True         18
25               CatBoost_BAG_L1      -0.319078  -0.310601  root_mean_squared_error        0.161313       0.007174   1.768012                 0.161313                0.007174           1.768012            1       True          4
26          CatBoost_r177_BAG_L2      -0.319195  -0.303516  root_mean_squared_error        1.151975       0.702866  42.859535                 0.018740                0.037372           3.518131            2       True        117
27          LightGBM_r161_BAG_L1      -0.319266  -0.316374  root_mean_squared_error        0.033723       0.023098   2.570781                 0.033723                0.023098           2.570781            1       True         36
28          CatBoost_r143_BAG_L1      -0.319280  -0.311325  root_mean_squared_error        0.014354       0.008366   2.570936                 0.014354                0.008366           2.570936            1       True         70
29          CatBoost_r137_BAG_L2      -0.319295  -0.301613  root_mean_squared_error        1.147935       0.692834  41.941060                 0.014699                0.027340           2.599656            2       True        126
30          LightGBM_r196_BAG_L2      -0.319317  -0.303025  root_mean_squared_error        1.598369       1.146601  59.598989                 0.465133                0.481107          20.257585            2       True        147
31            XGBoost_r49_BAG_L1      -0.319420  -0.318078  root_mean_squared_error        0.044513       0.034160   1.397263                 0.044513                0.034160           1.397263            1       True         66
32          CatBoost_r167_BAG_L1      -0.319694  -0.310835  root_mean_squared_error        0.014489       0.009570   3.028347                 0.014489                0.009570           3.028347            1       True         42
33   NeuralNetFastAI_r102_BAG_L2      -0.319739  -0.305402  root_mean_squared_error        1.213835       0.761870  48.784751                 0.080600                0.096376           9.443347            2       True        127
34   NeuralNetFastAI_r156_BAG_L1      -0.319863  -0.314255  root_mean_squared_error        0.120857       0.090664   7.826243                 0.120857                0.090664           7.826243            1       True         39
35           CatBoost_r12_BAG_L1      -0.319908  -0.312301  root_mean_squared_error        0.017570       0.009331   4.138074                 0.017570                0.009331           4.138074            1       True         92
36           LightGBM_r96_BAG_L2      -0.319968  -0.302138  root_mean_squared_error        1.197451       0.740194  43.277133                 0.064215                0.074700           3.935729            2       True        122
37   NeuralNetFastAI_r145_BAG_L1      -0.320029  -0.309510  root_mean_squared_error        0.082484       0.072978   5.530867                 0.082484                0.072978           5.530867            1       True         24
38        ExtraTrees_r126_BAG_L1      -0.320094  -0.311348  root_mean_squared_error        0.046409       0.056377   0.858404                 0.046409                0.056377           0.858404            1       True         95
39        ExtraTrees_r172_BAG_L2      -0.320117  -0.304490  root_mean_squared_error        1.179836       0.720529  39.699075                 0.046600                0.055035           0.357671            2       True        139
40            XGBoost_r31_BAG_L1      -0.320181  -0.314775  root_mean_squared_error        0.067249       0.021997   1.001127                 0.067249                0.021997           1.001127            1       True         73
41           CatBoost_r70_BAG_L2      -0.320195  -0.302684  root_mean_squared_error        1.148907       0.692624  45.889993                 0.015671                0.027130           6.548589            2       True        145
42            CatBoost_r9_BAG_L1      -0.320278  -0.312677  root_mean_squared_error        0.024812       0.010680   7.705629                 0.024812                0.010680           7.705629            1       True         14
43          CatBoost_r198_BAG_L1      -0.320349  -0.312544  root_mean_squared_error        0.012394       0.006995   1.654097                 0.012394                0.006995           1.654097            1       True         99
44           CatBoost_r69_BAG_L1      -0.320375  -0.313303  root_mean_squared_error        0.011209       0.005998   1.291411                 0.011209                0.005998           1.291411            1       True         33
45            XGBoost_r22_BAG_L1      -0.320381  -0.315980  root_mean_squared_error        0.058421       0.021535   0.980437                 0.058421                0.021535           0.980437            1       True         79
46           CatBoost_r60_BAG_L1      -0.320482  -0.312238  root_mean_squared_error        0.016163       0.007195   1.192367                 0.016163                0.007195           1.192367            1       True         76
47          LightGBMLarge_BAG_L2      -0.320614  -0.318515  root_mean_squared_error        1.153378       0.681388  44.209575                 0.020142                0.015894           4.868170            2       True        116
48            XGBoost_r33_BAG_L1      -0.320692  -0.319323  root_mean_squared_error        0.079492       0.060500   4.785621                 0.079492                0.060500           4.785621            1       True         17
49           WeightedEnsemble_L2      -0.320747  -0.301557  root_mean_squared_error        0.621172       0.372795  28.249121                 0.002485                0.000211           0.007585            2       True        107
50   NeuralNetFastAI_r103_BAG_L2      -0.320865  -0.304843  root_mean_squared_error        1.176400       0.734913  44.502466                 0.043164                0.069419           5.161062            2       True        141
51          LightGBM_r121_BAG_L1      -0.320879  -0.316462  root_mean_squared_error        0.039828       0.023917   2.519357                 0.039828                0.023917           2.519357            1       True         83
52   NeuralNetFastAI_r143_BAG_L2      -0.320916  -0.306387  root_mean_squared_error        1.174724       0.733295  42.952315                 0.041488                0.067801           3.610911            2       True        144
53        ExtraTrees_r172_BAG_L1      -0.320926  -0.309739  root_mean_squared_error        0.051802       0.051123   0.350542                 0.051802                0.051123           0.350542            1       True         32
54          LightGBM_r131_BAG_L1      -0.321003  -0.315287  root_mean_squared_error        0.025472       0.018762   1.935326                 0.025472                0.018762           1.935326            1       True         12
55          LightGBM_r130_BAG_L1      -0.321020  -0.314309  root_mean_squared_error        0.011009       0.008454   0.956790                 0.011009                0.008454           0.956790            1       True         27
56          CatBoost_r177_BAG_L1      -0.321061  -0.313030  root_mean_squared_error        0.014194       0.007457   1.490952                 0.014194                0.007457           1.490952            1       True         10
57          CatBoost_r128_BAG_L1      -0.321071  -0.312007  root_mean_squared_error        0.024038       0.009611   6.654937                 0.024038                0.009611           6.654937            1       True         59
58   NeuralNetFastAI_r102_BAG_L1      -0.321182  -0.306394  root_mean_squared_error        0.124917       0.134479   9.174651                 0.124917                0.134479           9.174651            1       True         20
59            CatBoost_r6_BAG_L1      -0.321184  -0.312105  root_mean_squared_error        0.015886       0.007707   1.434437                 0.015886                0.007707           1.434437            1       True         81
60            XGBoost_r33_BAG_L2      -0.321200  -0.309516  root_mean_squared_error        1.209569       0.743691  47.882636                 0.076333                0.078197           8.541232            2       True        124
61         ExtraTrees_r49_BAG_L1      -0.321216  -0.311318  root_mean_squared_error        0.080066       0.061738   0.817935                 0.080066                0.061738           0.817935            1       True         52
62            XGBoost_r89_BAG_L2      -0.321227  -0.305942  root_mean_squared_error        1.162387       0.703847  40.569615                 0.029151                0.038353           1.228211            2       True        132
63          LightGBM_r188_BAG_L2      -0.321231  -0.300440  root_mean_squared_error        1.898484       1.480778  71.564762                 0.765248                0.815284          32.223358            2       True        130
64            XGBoost_r98_BAG_L1      -0.321333  -0.316071  root_mean_squared_error        0.074174       0.066755   4.422621                 0.074174                0.066755           4.422621            1       True         45
65          ExtraTreesMSE_BAG_L2      -0.321355  -0.303161  root_mean_squared_error        1.192314       0.726412  39.690285                 0.059078                0.060918           0.348881            2       True        112
66           WeightedEnsemble_L3      -0.321377  -0.291126  root_mean_squared_error        1.620845       1.237684  97.777110                 0.001218                0.000255           0.008368            3       True        152
67    NeuralNetFastAI_r95_BAG_L1      -0.321404  -0.319962  root_mean_squared_error        0.092470       0.091561   5.453646                 0.092470                0.091561           5.453646            1       True         43
68          CatBoost_r163_BAG_L1      -0.321639  -0.312510  root_mean_squared_error        0.014898       0.006625   1.119919                 0.014898                0.006625           1.119919            1       True         98
69    NeuralNetFastAI_r11_BAG_L2      -0.321785  -0.303384  root_mean_squared_error        1.218667       0.749121  47.320832                 0.085431                0.083627           7.979427            2       True        137
70            XGBoost_r34_BAG_L1      -0.321861  -0.317463  root_mean_squared_error        0.071066       0.047482   2.854579                 0.071066                0.047482           2.854579            1       True        103
71                XGBoost_BAG_L2      -0.321883  -0.309376  root_mean_squared_error        1.177167       0.706039  41.314707                 0.043931                0.040545           1.973303            2       True        114
72   NeuralNetFastAI_r134_BAG_L1      -0.321885  -0.308982  root_mean_squared_error        0.151458       0.142972  23.448537                 0.151458                0.142972          23.448537            1       True         55
73        NeuralNetFastAI_BAG_L1      -0.321971  -0.309623  root_mean_squared_error        0.475943       0.064023   3.875817                 0.475943                0.064023           3.875817            1       True          6
74           CatBoost_r70_BAG_L1      -0.322012  -0.312461  root_mean_squared_error        0.018924       0.009120   3.158588                 0.018924                0.009120           3.158588            1       True         38
75      RandomForest_r127_BAG_L1      -0.322124  -0.315987  root_mean_squared_error        0.047848       0.054059   0.938493                 0.047848                0.054059           0.938493            1       True         54
76                XGBoost_BAG_L1      -0.322145  -0.319778  root_mean_squared_error        0.058318       0.025294   1.031572                 0.058318                0.025294           1.031572            1       True          7
77           CatBoost_r50_BAG_L1      -0.322147  -0.312324  root_mean_squared_error        0.019261       0.007618   1.708871                 0.019261                0.007618           1.708871            1       True         29
78          CatBoost_r180_BAG_L1      -0.322175  -0.312678  root_mean_squared_error        0.020513       0.010473   4.181104                 0.020513                0.010473           4.181104            1       True         85

(raylet) Task _ray_fit failed. There are 2 retries remaining, so the task will be retried. Error:

	-0.3198	 = Validation score   (-root_mean_squared_error)
	1.25s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 1122.22s of the 1122.21s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.3424	 = Validation score   (-root_mean_squared_error)
	6.27s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 1114.77s of the 1114.76s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.22%)
	-0.3269	 = Validation score   (-root_mean_squared_error)
	6.21s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 1107.15s of the 1107.14s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=4.92%)
	-0.3113	 = Validation score   (-root_mean_squared_error)
	2.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 1103.85s of the 1103.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.3309	 = Validation score   (-root_mean_squared_error)
	6.3s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 1096.43s of the 1096.42s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.45%)
	-0.3161	 = Validation score   (-root_mean_squared_error)
	2.01s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 1093.19s of the 1093.18s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3156	 = Validation score   (-root_mean_squared_error)
	6.27s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 1085.72s of the 1085.71s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=6.84%)
	-0.311	 = Validation score   (-root_mean_squared_error)
	9.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 1074.83s of the 1074.82s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.14%)
	-0.3094	 = Validation score   (-root_mean_squared_error)
	1.33s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetTorch_r22_BAG_L1 ... Training model for up to 1072.22s of the 1072.21s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.332	 = Validation score   (-root_mean_squared_error)
	7.89s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_r33_BAG_L1 ... Training model for up to 1063.14s of the 1063.13s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.05%)
	-0.3174	 = Validation score   (-root_mean_squared_error)
	4.63s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTrees_r42_BAG_L1 ... Training model for up to 1057.22s of the 1057.20s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3117	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r137_BAG_L1 ... Training model for up to 1056.77s of the 1056.76s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=4.80%)
	-0.3112	 = Validation score   (-root_mean_squared_error)
	2.11s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r102_BAG_L1 ... Training model for up to 1053.54s of the 1053.53s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3095	 = Validation score   (-root_mean_squared_error)
	9.96s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: CatBoost_r13_BAG_L1 ... Training model for up to 1042.36s of the 1042.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.58%)
	-0.3118	 = Validation score   (-root_mean_squared_error)
	11.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForest_r195_BAG_L1 ... Training model for up to 1029.94s of the 1029.92s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3188	 = Validation score   (-root_mean_squared_error)
	0.46s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r188_BAG_L1 ... Training model for up to 1029.37s of the 1029.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.95%)
	-0.3104	 = Validation score   (-root_mean_squared_error)
	2.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r145_BAG_L1 ... Training model for up to 1025.98s of the 1025.97s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3077	 = Validation score   (-root_mean_squared_error)
	5.57s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: XGBoost_r89_BAG_L1 ... Training model for up to 1019.18s of the 1019.17s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.22%)
	-0.3138	 = Validation score   (-root_mean_squared_error)
	0.76s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r30_BAG_L1 ... Training model for up to 1016.88s of the 1016.87s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.33	 = Validation score   (-root_mean_squared_error)
	11.47s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBM_r130_BAG_L1 ... Training model for up to 1004.09s of the 1004.08s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.70%)
	-0.3138	 = Validation score   (-root_mean_squared_error)
	1.1s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r86_BAG_L1 ... Training model for up to 1001.83s of the 1001.82s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.3395	 = Validation score   (-root_mean_squared_error)
	6.86s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: CatBoost_r50_BAG_L1 ... Training model for up to 993.68s of the 993.67s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.28%)
	-0.311	 = Validation score   (-root_mean_squared_error)
	1.47s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r11_BAG_L1 ... Training model for up to 990.91s of the 990.90s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3061	 = Validation score   (-root_mean_squared_error)
	9.09s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: XGBoost_r194_BAG_L1 ... Training model for up to 980.41s of the 980.40s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.34%)
	-0.321	 = Validation score   (-root_mean_squared_error)
	1.69s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTrees_r172_BAG_L1 ... Training model for up to 977.25s of the 977.24s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3114	 = Validation score   (-root_mean_squared_error)
	0.37s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r69_BAG_L1 ... Training model for up to 976.80s of the 976.79s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=4.84%)
	-0.3104	 = Validation score   (-root_mean_squared_error)
	1.99s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r103_BAG_L1 ... Training model for up to 973.60s of the 973.59s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3117	 = Validation score   (-root_mean_squared_error)
	4.8s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetTorch_r14_BAG_L1 ... Training model for up to 967.51s of the 967.49s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3251	 = Validation score   (-root_mean_squared_error)
	3.86s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBM_r161_BAG_L1 ... Training model for up to 962.34s of the 962.33s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=2.83%)
	-0.3162	 = Validation score   (-root_mean_squared_error)
	2.64s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI_r143_BAG_L1 ... Training model for up to 958.17s of the 958.16s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3119	 = Validation score   (-root_mean_squared_error)
	3.5s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 953.43s of the 953.42s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=7.57%)
	-0.3121	 = Validation score   (-root_mean_squared_error)
	3.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r156_BAG_L1 ... Training model for up to 948.16s of the 948.15s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3119	 = Validation score   (-root_mean_squared_error)
	9.91s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBM_r196_BAG_L1 ... Training model for up to 936.96s of the 936.95s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.10%)
	-0.3091	 = Validation score   (-root_mean_squared_error)
	4.5s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForest_r39_BAG_L1 ... Training model for up to 931.06s of the 931.05s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.317	 = Validation score   (-root_mean_squared_error)
	0.4s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r167_BAG_L1 ... Training model for up to 930.59s of the 930.57s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.06%)
	-0.3108	 = Validation score   (-root_mean_squared_error)
	2.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r95_BAG_L1 ... Training model for up to 926.59s of the 926.58s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3166	 = Validation score   (-root_mean_squared_error)
	5.68s	 = Training   runtime
	0.16s	 = Validation runtime
Fitting model: NeuralNetTorch_r41_BAG_L1 ... Training model for up to 919.60s of the 919.59s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.3321	 = Validation score   (-root_mean_squared_error)
	5.51s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: XGBoost_r98_BAG_L1 ... Training model for up to 912.89s of the 912.88s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.58%)
	-0.3151	 = Validation score   (-root_mean_squared_error)
	4.83s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_r15_BAG_L1 ... Training model for up to 906.73s of the 906.72s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.19%)
	-0.3145	 = Validation score   (-root_mean_squared_error)
	1.26s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r158_BAG_L1 ... Training model for up to 904.30s of the 904.29s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
	-0.323	 = Validation score   (-root_mean_squared_error)
	10.07s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: CatBoost_r86_BAG_L1 ... Training model for up to 893.04s of the 893.03s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.46%)
	-0.3119	 = Validation score   (-root_mean_squared_error)
	7.39s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r37_BAG_L1 ... Training model for up to 884.47s of the 884.45s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3084	 = Validation score   (-root_mean_squared_error)
	4.81s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetTorch_r197_BAG_L1 ... Training model for up to 878.50s of the 878.49s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3326	 = Validation score   (-root_mean_squared_error)
	4.0s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost_r49_BAG_L1 ... Training model for up to 873.12s of the 873.11s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.74%)
	-0.3118	 = Validation score   (-root_mean_squared_error)
	1.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: ExtraTrees_r49_BAG_L1 ... Training model for up to 870.51s of the 870.50s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3114	 = Validation score   (-root_mean_squared_error)
	0.4s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBM_r143_BAG_L1 ... Training model for up to 870.02s of the 870.01s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=1.41%)
	-0.3175	 = Validation score   (-root_mean_squared_error)
	1.88s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForest_r127_BAG_L1 ... Training model for up to 866.97s of the 866.96s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3158	 = Validation score   (-root_mean_squared_error)
	0.45s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetFastAI_r134_BAG_L1 ... Training model for up to 866.45s of the 866.44s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3107	 = Validation score   (-root_mean_squared_error)
	23.0s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: RandomForest_r34_BAG_L1 ... Training model for up to 842.27s of the 842.26s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3149	 = Validation score   (-root_mean_squared_error)
	0.34s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBM_r94_BAG_L1 ... Training model for up to 841.86s of the 841.85s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.15%)
	-0.3093	 = Validation score   (-root_mean_squared_error)
	1.04s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch_r143_BAG_L1 ... Training model for up to 839.66s of the 839.65s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3247	 = Validation score   (-root_mean_squared_error)
	9.69s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost_r128_BAG_L1 ... Training model for up to 828.70s of the 828.69s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=5.58%)
	-0.3138	 = Validation score   (-root_mean_squared_error)
	8.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetFastAI_r111_BAG_L1 ... Training model for up to 819.39s of the 819.38s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3106	 = Validation score   (-root_mean_squared_error)
	8.91s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetTorch_r31_BAG_L1 ... Training model for up to 809.34s of the 809.33s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.02%)
	-0.3325	 = Validation score   (-root_mean_squared_error)
	5.88s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTrees_r4_BAG_L1 ... Training model for up to 802.21s of the 802.20s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=16, gpus=0
	-0.3135	 = Validation score   (-root_mean_squared_error)
	0.35s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI_r65_BAG_L1 ... Training model for up to 801.80s of the 801.78s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.03%)
	-0.3204	 = Validation score   (-root_mean_squared_error)
	3.53s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: NeuralNetFastAI_r88_BAG_L1 ... Training model for up to 797.14s of the 797.13s of remaining time.

In [20]:
leaderboard

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost_r69_BAG_L1,-0.305733,-0.310358,root_mean_squared_error,0.010232,0.007800,1.990010,0.010232,0.007800,1.990010,1,True,33
1,NeuralNetFastAI_r160_BAG_L1,-0.306288,-0.307994,root_mean_squared_error,0.061265,0.118421,4.706770,0.061265,0.118421,4.706770,1,True,75
2,LightGBM_r96_BAG_L1,-0.306805,-0.309427,root_mean_squared_error,0.031769,0.033026,1.331033,0.031769,0.033026,1.331033,1,True,15
3,XGBoost_r89_BAG_L1,-0.306846,-0.313833,root_mean_squared_error,0.041011,0.024069,0.758708,0.041011,0.024069,0.758708,1,True,25
4,CatBoost_r60_BAG_L1,-0.306888,-0.310666,root_mean_squared_error,0.010649,0.007304,1.665435,0.010649,0.007304,1.665435,1,True,76
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,NeuralNetTorch_r31_BAG_L1,-0.337604,-0.332468,root_mean_squared_error,0.045413,0.052477,5.877593,0.045413,0.052477,5.877593,1,True,61
103,NeuralNetTorch_r76_BAG_L1,-0.339503,-0.329801,root_mean_squared_error,0.040082,0.063499,4.126857,0.040082,0.063499,4.126857,1,True,86
104,NeuralNetTorch_r19_BAG_L1,-0.340220,-0.331017,root_mean_squared_error,0.077166,0.065811,3.972404,0.077166,0.065811,3.972404,1,True,101
105,NeuralNetTorch_r89_BAG_L1,-0.341080,-0.336418,root_mean_squared_error,0.094904,0.144104,8.368266,0.094904,0.144104,8.368266,1,True,106
106,NeuralNetTorch_r86_BAG_L1,-0.342045,-0.339542,root_mean_squared_error,0.087533,0.090660,6.863520,0.087533,0.090660,6.863520,1,True,28

In [21]:
metrics

{'rmse': np.float64(0.30747117806625385),
 'mae': 0.23923081665285262,
 'r2': 0.26678992693168113}

In [23]:
leaderboard.head()

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost_r69_BAG_L1,-0.305733,-0.310358,root_mean_squared_error,0.010232,0.007800,1.990010,0.010232,0.007800,1.990010,1,True,33
1,NeuralNetFastAI_r160_BAG_L1,-0.306288,-0.307994,root_mean_squared_error,0.061265,0.118421,4.706770,0.061265,0.118421,4.706770,1,True,75
2,LightGBM_r96_BAG_L1,-0.306805,-0.309427,root_mean_squared_error,0.031769,0.033026,1.331033,0.031769,0.033026,1.331033,1,True,15
3,XGBoost_r89_BAG_L1,-0.306846,-0.313833,root_mean_squared_error,0.041011,0.024069,0.758708,0.041011,0.024069,0.758708,1,True,25
4,CatBoost_r60_BAG_L1,-0.306888,-0.310666,root_mean_squared_error,0.010649,0.007304,1.665435,0.010649,0.007304,1.665435,1,True,76