### Carregando Dataset

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('../Datasets/Dados/VIF - Final até agora/dataset_modelo_2022.csv', sep=';')
df.head()

,NU_ANO_CENSO,CO_MUNICIPIO,NO_MUNICIPIO,SG_UF,TAXA_CRE_INT,PROP_ESC_PUBLICA,PROP_ESC_URBANA,PROP_MAT_BRANCA,PROP_MAT_PRETA,PROP_MAT_PARDA,...,TAXA_OCUP_FEM,TAXA_OCUP_MASC,PROP_MAES_JOVENS,PROP_DOM_SEM_CONJUGE_MULHER,PERC_RENDA_OUTRAS_FONTES,RENDA_MEDIANA_RESPONSAVEL,IDH_PROP_POBREZA_CRIANCAS,IDH_GINI,IDH_EXPECT_ANOS_ESTUDO,IDH_RAZAO_DEPENDENCIA
0,2022,2100055,Açailândia,MA,0.135303,0.817391,0.695652,0.145048,0.016151,0.836538,...,0.374363,0.631811,0.014926,0.151264,21.47,1212.0,36.65,0.56,9.34,55.43
1,2022,2100105,Afonso Cunha,MA,0.864198,1.000000,0.240000,0.040602,0.023903,0.932875,...,0.275815,0.419239,0.037771,0.124486,43.42,1200.0,78.75,0.59,8.62,74.96
2,2022,2100154,Água Doce do Maranhão,MA,0.000000,0.969697,0.242424,0.090790,0.014749,0.890528,...,0.311589,0.473313,0.022701,0.110829,45.26,1200.0,71.85,0.59,8.07,65.18
3,2022,2100204,Alcântara,MA,0.000000,0.982143,0.142857,0.066054,0.067747,0.865231,...,0.261981,0.421794,0.021182,0.150556,53.12,1200.0,67.97,0.59,8.21,59.08
4,2022,2100303,Aldeias Altas,MA,0.008863,0.982759,0.241379,0.043889,0.033889,0.919074,...,0.213457,0.359990,0.023668,0.165767,43.84,1200.0,73.89,0.59,6.68,70.61

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1781 entries, 0 to 1780
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   NU_ANO_CENSO                   1781 non-null   int64
 1   CO_MUNICIPIO                   1781 non-null   int64
 2   NO_MUNICIPIO                   1781 non-null   str
 3   SG_UF                          1781 non-null   str
 4   TAXA_CRE_INT                   1781 non-null   float64
 5   PROP_ESC_PUBLICA               1781 non-null   float64
 6   PROP_ESC_URBANA                1781 non-null   float64
 7   PROP_MAT_BRANCA                1781 non-null   float64
 8   PROP_MAT_PRETA                 1781 non-null   float64
 9   PROP_MAT_PARDA                 1781 non-null   float64
 10  PROP_MAT_INDIGENA              1781 non-null   float64
 11  COBERTURA_CRECHE_0_3           1781 non-null   float64
 12  ESCOLAS_CRECHE_POR_1000_CRIAN  1781 non-null   float64
 13  MEDIA_MAT_0_3_POR_ESCOLA       1781 non-null   int64
 14  LOG_POP_TOTAL                  1781 non-null   float64
 15  PIB_PC                         1781 non-null   float64
 16  LOG_PIB_PC                     1781 non-null   float64
 17  TAXA_OCUP_FEM                  1781 non-null   float64
 18  TAXA_OCUP_MASC                 1781 non-null   float64
 19  PROP_MAES_JOVENS               1781 non-null   float64
 20  PROP_DOM_SEM_CONJUGE_MULHER    1781 non-null   float64
 21  PERC_RENDA_OUTRAS_FONTES       1781 non-null   float64
 22  RENDA_MEDIANA_RESPONSAVEL      1781 non-null   float64
 23  IDH_PROP_POBREZA_CRIANCAS      1781 non-null   float64
 24  IDH_GINI                       1781 non-null   float64
 25  IDH_EXPECT_ANOS_ESTUDO         1781 non-null   float64
 26  IDH_RAZAO_DEPENDENCIA          1781 non-null   float64
dtypes: float64(22), int64(3), str(2)
memory usage: 375.8 KB

In [4]:
for col in df.columns:
    print(col, ':', df[col].nunique())

NU_ANO_CENSO : 1
CO_MUNICIPIO : 1781
NO_MUNICIPIO : 1714
SG_UF : 9
TAXA_CRE_INT : 1083
PROP_ESC_PUBLICA : 440
PROP_ESC_URBANA : 626
PROP_MAT_BRANCA : 1781
PROP_MAT_PRETA : 1748
PROP_MAT_PARDA : 1769
PROP_MAT_INDIGENA : 1105
COBERTURA_CRECHE_0_3 : 1751
ESCOLAS_CRECHE_POR_1000_CRIAN : 1652
MEDIA_MAT_0_3_POR_ESCOLA : 42
LOG_POP_TOTAL : 1725
PIB_PC : 1780
LOG_PIB_PC : 1779
TAXA_OCUP_FEM : 1773
TAXA_OCUP_MASC : 1776
PROP_MAES_JOVENS : 1725
PROP_DOM_SEM_CONJUGE_MULHER : 1760
PERC_RENDA_OUTRAS_FONTES : 1387
RENDA_MEDIANA_RESPONSAVEL : 51
IDH_PROP_POBREZA_CRIANCAS : 1449
IDH_GINI : 37
IDH_EXPECT_ANOS_ESTUDO : 363
IDH_RAZAO_DEPENDENCIA : 1231

NU_ANO_CENSO  vai ser dropada por ser constante. CO_MUNICIPIO e NO_MUNICIPIO são IDs (Vou manter só o nome msm pra ajudar a plotar). SG_UF Vamos tentar fazer um OHE depois e ver se dá pra usar.

In [5]:
X = df.drop(columns = ['TAXA_CRE_INT', 'NU_ANO_CENSO', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'SG_UF'])
y = df['TAXA_CRE_INT']

### Normalizando os dados

In [6]:
scaler = StandardScaler() # deixar geral com média 0 e desvio padrão 1. 

X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(
    X_scaled,
    columns=X.columns,
    index=X.index
)

In [7]:
X_scaled

,PROP_ESC_PUBLICA,PROP_ESC_URBANA,PROP_MAT_BRANCA,PROP_MAT_PRETA,PROP_MAT_PARDA,PROP_MAT_INDIGENA,COBERTURA_CRECHE_0_3,ESCOLAS_CRECHE_POR_1000_CRIAN,MEDIA_MAT_0_3_POR_ESCOLA,LOG_POP_TOTAL,...,TAXA_OCUP_FEM,TAXA_OCUP_MASC,PROP_MAES_JOVENS,PROP_DOM_SEM_CONJUGE_MULHER,PERC_RENDA_OUTRAS_FONTES,RENDA_MEDIANA_RESPONSAVEL,IDH_PROP_POBREZA_CRIANCAS,IDH_GINI,IDH_EXPECT_ANOS_ESTUDO,IDH_RAZAO_DEPENDENCIA
0,-0.743785,1.270983,-0.400737,-0.540101,0.700671,-0.146408,-0.690487,-1.041904,0.669534,2.005997,...,1.184563,1.470537,-0.287719,0.168368,-2.496393,0.229597,-1.705247,0.705490,0.508022,-0.297924
1,0.840941,-0.926577,-1.176642,-0.399678,1.398523,-0.161043,0.480759,0.621717,-0.463041,-0.870616,...,-0.163226,-0.574113,2.512070,-0.978068,-0.281062,0.090791,1.887949,1.313072,-0.399108,2.647509
2,0.577964,-0.914887,-0.803807,-0.565497,1.091767,-0.149102,-0.835632,0.135556,-0.948430,-0.183861,...,0.326036,-0.053996,0.665153,-1.562760,-0.095357,0.090791,1.299040,1.313072,-1.092055,1.172530
3,0.685974,-1.395088,-0.987565,0.394528,0.908519,-0.158185,-0.945106,0.755381,-1.110227,0.238898,...,-0.352426,-0.549537,0.478990,0.138057,0.697923,0.090791,0.967886,1.313072,-0.915669,0.252553
4,0.691320,-0.919927,-1.152223,-0.218788,1.298550,-0.150139,-0.107714,-0.335717,0.022348,0.472675,...,-1.016063,-1.144007,0.783664,0.789280,-0.238673,0.090791,1.473153,1.313072,-2.843320,1.991460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1776,-2.456793,1.062866,0.349961,0.464866,-0.444293,-0.151250,-1.248053,-0.891742,-0.463041,3.263582,...,2.415335,1.814586,-0.586143,0.987331,-2.374272,0.229597,-2.252335,0.502963,-0.235321,-1.573826
1777,0.384188,0.961966,-1.055843,-0.323562,1.250335,-0.143204,-1.062125,0.039347,-0.948430,-0.430931,...,0.429580,0.887187,-1.198064,1.367293,-0.423368,0.090791,-0.168964,-0.104618,0.054457,0.294782
1778,0.585697,-0.665572,0.141971,0.745421,-0.406770,-0.155746,0.295510,0.375871,-0.463041,-0.117507,...,-0.276276,0.165540,0.082032,-1.265512,-0.255830,0.090791,0.581255,1.313072,-1.255843,-0.211959
1779,0.700970,-1.072822,-1.076346,0.367610,0.992309,-0.155928,-0.642249,0.007343,-0.786634,0.522843,...,-0.083356,0.857408,0.631205,-0.823729,-0.378960,-1.065930,-0.319178,-1.522308,-2.036982,0.050460
1780,0.523448,-0.966574,-0.870725,0.865320,0.572977,-0.117537,0.522952,0.601486,-0.463041,1.131460,...,0.620613,0.540031,0.874968,0.938439,-0.563655,0.090791,0.106714,0.705490,-0.298316,0.845260

### Montando Funções de Seleção de Features

In [8]:
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE, SequentialFeatureSelector, SelectFromModel
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import make_scorer, mean_squared_error, r2_score

In [9]:
def rmse_score(y_true, y_pred):
    return -np.sqrt(mean_squared_error(y_true, y_pred))

In [10]:
def rfe_search(X, y, cv=None, random_state=42):    
    results = []

    for i in range(1, len(X.columns)+1):
        selector = RFE(
            estimator=Ridge(random_state=random_state),
            n_features_to_select=i
        )

        pipeline = Pipeline([
            ("selector", selector),
            ("model", Ridge(random_state=random_state))
        ])

        rmse_scores = cross_val_score(
            pipeline, 
            X,
            y, 
            cv=cv,
            scoring="neg_root_mean_squared_error",
            n_jobs=os.cpu_count()//2
        )

        r2_scores = cross_val_score(
            pipeline,
            X,
            y,
            cv=cv,
            scoring="r2",
            n_jobs=os.cpu_count()//2
        )

        selector.fit(X, y)

        selected_features = X.columns[selector.get_support()].to_list() # o método support_ de selector pega os nomes das colunas que foram selecionadas pelo RFE.

        results.append({
            "method": "RFE",
            "n_features": i,
            "selected_features": selected_features,
            "rmse_mean": -rmse_scores.mean(),
            "rmse_std": rmse_scores.std(),
            "r2_mean": r2_scores.mean(),
            "r2_std": r2_scores.std()
        })

    return pd.DataFrame(results)

In [11]:
def sfs_search(X, y, cv, direction="forward", random_state=42):
    results = []

    for i in range(1, len(X.columns)):
        selector = SequentialFeatureSelector(
            estimator=Ridge(random_state=random_state),
            n_features_to_select=i,
            direction=direction,
            scoring="neg_root_mean_squared_error",
            cv=cv,
            n_jobs=os.cpu_count()//2
        )

        pipeline = Pipeline([
            ("selector", selector),
            ("model", Ridge(random_state=random_state))
        ])

        rmse_scores = cross_val_score(
            pipeline,
            X,
            y,
            cv=cv,
            scoring="neg_root_mean_squared_error", 
            n_jobs=os.cpu_count()//2
        )

        r2_scores = cross_val_score(
            pipeline,
            X,
            y,
            cv=cv,
            scoring="r2",
            n_jobs=os.cpu_count()//2
        )

        selector.fit(X, y)

        selected_features = X.columns[selector.get_support()].to_list() 

        results.append({
            "method": f"RFS_{direction}",
            "n_features": i,
            "selected_features": selected_features,
            "rmse_mean": -rmse_scores.mean(),
            "rmse_std": rmse_scores.std(),
            "r2_mean": r2_scores.mean(),
            "r2_std": r2_scores.std()
        })

    return pd.DataFrame(results)

In [15]:
def lasso_search(X, y, cv, random_state=42):
    results = []

    alphas = np.logspace(-4, 2, 30)

    for alpha in alphas:
        selector = SelectFromModel(
            estimator=Lasso(
                alpha = alpha,
                max_iter=100000,
                random_state=random_state
            ),
            threshold=1e-8
        )

        pipeline = Pipeline([
            ("selector", selector),
            ("model", Ridge(random_state=random_state))
        ])

        try:
            rmse_scores = cross_val_score(
                pipeline,
                X,
                y, 
                cv=cv,
                scoring="neg_root_mean_squared_error",
                n_jobs=os.cpu_count()//2
                )
            
            r2_scores = cross_val_score(
                pipeline,
                X,
                y,
                cv=cv,
                scoring="r2",
                n_jobs=os.cpu_count()//2
            )

            selector.fit(X, y)

            selected_features = X.columns[selector.get_support()].to_list()

            if len(selected_features) == 0:
                continue

            results.append({
                "method": "Lasso",
                "alpha": alpha,
                "n_features": len(selected_features),
                "selected_features": selected_features,
                "rmse_mean": -rmse_scores.mean(),
                "rmse_std": rmse_scores.std(),
                "r2_mean": r2_scores.mean(),
                "r2_std": r2_scores.std()
            })
        except ValueError:
            continue

    return pd.DataFrame(results)

In [18]:
def run_feature_selection(X, y): # Aqui já é esperado um X normalizado.
    X = X.select_dtypes(include=[np.number])

    cv = KFold(
        n_splits=5,
        shuffle=True, 
        random_state=42
    )

    print('Executando Recursive Feature Elimination...')
    rfe_results = rfe_search(X, y, cv)
    
    print('Executando Sequential Feature Selection...')
    sfs_results = sfs_search(X, y, cv)

    print('Executando "Lasso Selection"...')
    lasso_results = lasso_search(X, y, cv)

    results = pd.concat([
        rfe_results,
        sfs_results,
        lasso_results
        ],
        ignore_index=True
    )

    results_df = results.sort_values(
        by=["rmse_mean", "r2_mean"],
        ascending=[True, False]
    )

    best_result = results_df.iloc[0]

    return results_df, best_result

In [19]:
results_df, best_result = run_feature_selection(X_scaled, y)

Executando Recursive Feature Elimination...
Executando Sequential Feature Selection...
Executando "Lasso Selection"...

/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/model_selection/_validation.py:490: FitFailedWarning:
2 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py", line 1254, in fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<6 lines>...
        y_numeric=True,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 2919, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 1314, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 1106, in check_array
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Found array with 0 feature(s) (shape=(1424, 0)) while a minimum of 1 is required by Ridge.

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/model_selection/_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/pipeline.py", line 621, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/base.py", line 1336, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/linear_model/_ridge.py", line 1254, in fit
    X, y = validate_data(
           ~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<6 lines>...
        y_numeric=True,
        ^^^^^^^^^^^^^^^
    )
    ^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 2919, in validate_data
    X, y = check_X_y(X, y, **check_params)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 1314, in check_X_y
    X = check_array(
        X,
    ...<12 lines>...
        input_name="X",
    )
  File "/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/utils/validation.py", line 1106, in check_array
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Found array with 0 feature(s) (shape=(1425, 0)) while a minimum of 1 is required by Ridge.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(
/home/guilherme_fernandes/anaconda3/envs/ml_mest/lib/python3.14/site-packages/sklearn/feature_selection/_base.py:122: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  warnings.warn(

In [23]:
results_df.to_csv('../Results/feature_selection.csv')